# Generated by Django 2.0 on 2019-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20181213_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='perfis_bloqueados',
            field=models.ManyToManyField(related_name='_perfil_perfis_bloqueados_+', to='perfis.Perfil'),
        ),
    ]
