# Generated by Django 2.0 on 2019-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_auto_20190105_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
