# Generated by Django 2.0 on 2019-01-05 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_auto_20190105_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 5, 21, 44, 56, 955729, tzinfo=utc)),
        ),
    ]
