# Generated by Django 2.0 on 2019-01-06 02:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0007_auto_20190105_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 2, 41, 37, 233932, tzinfo=utc)),
        ),
    ]
