# Generated by Django 2.0 on 2019-01-06 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_auto_20190106_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 2, 45, 45, 708284, tzinfo=utc)),
        ),
    ]
