# Generated by Django 2.0 on 2019-01-06 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_auto_20190106_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 6, 4, 0, 13, 687608, tzinfo=utc)),
        ),
    ]
