# Generated by Django 2.0 on 2019-01-06 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0010_auto_20190106_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 6, 4, 2, 6, 564874, tzinfo=utc)),
        ),
    ]
