# Generated by Django 2.0 on 2019-01-06 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0012_auto_20190106_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='dt_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
