# Generated by Django 2.1.5 on 2019-01-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0013_auto_20190106_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_bloqueado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_que_estou_bloqueado', to='perfis.Perfil')),
                ('perfil_que_bloqueia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_que_bloqueei', to='perfis.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos_bloqueados',
            field=models.ManyToManyField(related_name='meus_contatos_bloqueados', through='perfis.Bloqueio', to='perfis.Perfil'),
        ),
    ]
