# Generated by Django 2.0 on 2019-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0014_auto_20190108_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-dt_publicacao']},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='perfis_bloqueados',
        ),
        migrations.AddField(
            model_name='perfil',
            name='img_perfil',
            field=models.ImageField(blank=True, upload_to='static/img/perfil/'),
        ),
    ]
