# Generated by Django 2.0 on 2019-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_url', models.CharField(max_length=255)),
                ('url_encurtada', models.CharField(max_length=50)),
            ],
        ),
    ]
